# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader = "javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion = "[36,)" #mandatory
license = "All rights reserved. SCP concepts belong to their authors"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId = "scp_restoration" #mandatory
#version number of the mod
version = "0.8.3" #mandatory
# A display name for the mod
displayName = "SCP Restoration" #mandatory
# A text field displayed in the mod UI
authors = "Alexiy" #optional
credits = "Totemaster"
logoFile = "scp_restoration.png"
# The description text for the mod (#mandatory)
description = '''
Adds objects from the SCP wiki.
The objects generate in containement chambers in the world; their rarity can be adjusted.
'''
[[dependencies.scp_restoration]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
[[dependencies.scp_restoration]]
modId = "satako"
mandatory = true
versionRange = "[4.2,)"
ordering = "NONE"
side = "BOTH"
